<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('productos_solicitud_importados_aca', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->softDeletes();
            $table->integer('id_solicitud');
            $table->integer('estado_cl')->default(1);
            $table->longText('observacion_solicitud')->nullable();
            $table->date('fecha_cierre')->nullable();
            $table->integer('id_proveedor')->nullable();
            $table->integer('id_seccion')->nullable();
            $table->string('seccion')->nullable();
            $table->integer('sap')->nullable();
            $table->string('version',10)->nullable();
            $table->string('product_name',50)->nullable();
            $table->string('product_name_spanish',50)->nullable();
            $table->string('claims_origin',50)->nullable();
            $table->string('comments',50)->nullable();
            $table->string('name_organic_certifying_number',50)->nullable();
            $table->string('plant_number_factory',50)->nullable();
            $table->string('net_weight',50)->nullable();
            $table->string('drained_weight',50)->nullable();
            $table->string('units_x_packaging',50)->nullable();
            $table->string('country',50)->nullable();
            $table->string('milking_country',50)->nullable();
            $table->string('expiration_date',50)->nullable();
            $table->string('name_adress_manufacturer',50)->nullable();
            $table->string('shelf_life',50)->nullable();
            $table->string('upc_bar_code',50)->nullable();
            $table->string('storage_conditions',50)->nullable();
            $table->string('method_preparation',50)->nullable();
            $table->string('name_supplier',50)->nullable();
            $table->longText('ingredients')->nullable();
            $table->decimal('porcent_organic_ingredients', 5, 2)->nullable();
            $table->decimal('porcent_characterizing_ingredients', 5, 2)->nullable();
            $table->string('name_additive',50)->nullable();
            $table->decimal('porcent_additive', 5, 2)->nullable();
            $table->string('quantity_additive',50)->nullable();
            $table->string('indicate_additive_code',50)->nullable();
            $table->string('indicate_additive_functionality',50)->nullable();
            $table->string('vegetable_oil_fat_used',50)->nullable();
            $table->string('trans_fats_hydrogenated_origin',50)->nullable();
            $table->string('spices_herbs_used',50)->nullable();
            $table->string('quantity_sweetener_per_100_gr_ml',50)->nullable();
            $table->string('flavourings_aroma_natural_artificial',50)->nullable();
            $table->string('quantity_x_m_s_g',50)->nullable();
            $table->string('quantity_caffeine',50)->nullable();
            $table->string('any_extract_used',50)->nullable();
            $table->string('origin_gelatin',50)->nullable();
            $table->string('brix_final_product',50)->nullable();
            $table->string('brix_final_product_without_added_sugar',50)->nullable();
            $table->string('brix_fruit_greater_proportion_drink',50)->nullable();
            $table->string('names_colourings',50)->nullable();
            $table->decimal('minimum_porcent_cocoa_solids', 5, 2)->nullable();
            $table->decimal('porcent_cocoa_butter_cocoa_mass', 5, 2)->nullable();
            $table->string('contain_potential_allergens',50)->nullable();
            $table->string('cereals_gluten', 2)->nullable();
            $table->longText('cereals_gluten_list')->nullable();
            $table->string('crustacean_products', 2)->nullable();
            $table->longText('crustacean_products_list')->nullable();
            $table->string('egg_derivatives', 2)->nullable();
            $table->longText('egg_derivatives_list')->nullable();
            $table->string('fish_derivatives', 2)->nullable();
            $table->longText('fish_derivatives_list')->nullable();
            $table->string('peanuts_soy_derivatives', 2)->nullable();
            $table->longText('peanuts_soy_derivatives_list')->nullable();
            $table->string('milk_dairy_derivatives', 2)->nullable();
            $table->longText('milk_dairy_derivatives_list')->nullable();
            $table->string('nuts_derivatives', 2)->nullable();
            $table->longText('nuts_derivatives_list')->nullable();
            $table->string('sulfites_derivatives', 2)->nullable();
            $table->longText('sulfites_derivatives_list')->nullable();
            $table->string('total_plate_count',50)->nullable();
            $table->string('coliform',50)->nullable();
            $table->string('e_coli',50)->nullable();
            $table->string('e_coli_100',50)->nullable();
            $table->string('e_coli_0157_h7',50)->nullable();
            $table->string('campylobacter',50)->nullable();
            $table->string('bacillus_cereus',50)->nullable();
            $table->string('staphylococcus',50)->nullable();
            $table->string('clostridium_perfringens',50)->nullable();
            $table->string('listeria_monocytogenes',50)->nullable();
            $table->string('enterobacteria',50)->nullable();
            $table->string('mold',50)->nullable();
            $table->string('yeast',50)->nullable();
            $table->string('mold_count',50)->nullable();
            $table->string('yeast_count',50)->nullable();
            $table->string('salmonella_25',50)->nullable();
            $table->string('salmonella_50',50)->nullable();
            $table->string('lactobacillus',50)->nullable();
            $table->string('aerobic_anaerobic_mesophilic_microorganisms',50)->nullable();
            $table->string('aerobic_anaerobic_thermophilic_microorganisms',50)->nullable();
            $table->string('thermophilic_commercial_sterility',50)->nullable();
            $table->string('anaerobic_spores_reducing_sulfites',50)->nullable();
            $table->string('cronobacter_10g',50)->nullable();
            $table->string('ph',50)->nullable();
            $table->decimal('porcent_aw', 5, 2)->nullable();
            $table->string('type_primary_packaging',50)->nullable();
            $table->string('type_secundary_packaging',50)->nullable();
            $table->string('type_controls_sealing_air_tightness_primary_packaging',50)->nullable();
            $table->string('product_type',50)->nullable();
            $table->string('home_measure',50)->nullable();
            $table->decimal('serving_size', 7, 2)->nullable();
            $table->decimal('servings_per_container', 7, 2)->nullable();
            $table->decimal('energy_100', 7, 2)->nullable();
            $table->decimal('proteins_100', 7, 2)->nullable();
            $table->decimal('total_fat_100', 7, 2)->nullable();
            $table->decimal('satured_fat_100', 7, 2)->nullable();
            $table->decimal('trans_fat_100', 7, 2)->nullable();
            $table->decimal('monosatured_fat_100', 7, 2)->nullable();
            $table->decimal('polyunsatured_fat_100', 7, 2)->nullable();
            $table->decimal('cholesterol_100', 7, 2)->nullable();
            $table->decimal('total_carbohydrate_100', 7, 2)->nullable();
            $table->decimal('available_carbohydrates_100', 7, 2)->nullable();
            $table->decimal('total_sugars_100', 7, 2)->nullable();
            $table->decimal('sucrose_100', 7, 2)->nullable();
            $table->decimal('lactos_100', 7, 2)->nullable();
            $table->decimal('poliols_100', 7, 2)->nullable();
            $table->decimal('total_dietary_fiber_100', 7, 2)->nullable();
            $table->decimal('soluble_fiber_100', 7, 2)->nullable();
            $table->decimal('insoluble_fiber_100', 7, 2)->nullable();
            $table->decimal('sodium_100', 7, 2)->nullable();
            $table->decimal('energy_serving', 7, 2)->nullable();
            $table->decimal('proteins_serving', 7, 2)->nullable();
            $table->decimal('total_fat_serving', 7, 2)->nullable();
            $table->decimal('satured_fat_serving', 7, 2)->nullable();
            $table->decimal('trans_fat_serving', 7, 2)->nullable();
            $table->decimal('monosatured_fat_serving', 7, 2)->nullable();
            $table->decimal('polyunsatured_fat_serving', 7, 2)->nullable();
            $table->decimal('cholesterol_serving', 7, 2)->nullable();
            $table->decimal('total_carbohydrate_serving', 7, 2)->nullable();
            $table->decimal('available_carbohydrates_serving', 7, 2)->nullable();
            $table->decimal('total_sugars_serving', 7, 2)->nullable();
            $table->decimal('sucrose_serving', 7, 2)->nullable();
            $table->decimal('lactos_serving', 7, 2)->nullable();
            $table->decimal('poliols_serving', 7, 2)->nullable();
            $table->decimal('total_dietary_fiber_serving', 7, 2)->nullable();
            $table->decimal('soluble_fiber_serving', 7, 2)->nullable();
            $table->decimal('insoluble_fiber_serving', 7, 2)->nullable();
            $table->decimal('sodium_serving', 7, 2)->nullable();
            $table->string('home_measure_reconstitued',50)->nullable();
            $table->decimal('serving_size_reconstitued', 7, 2)->nullable();
            $table->decimal('servings_per_container_reconstitued', 7, 2)->nullable();
            $table->decimal('energy_100_reconstitued', 7, 2)->nullable();
            $table->decimal('proteins_100_reconstitued', 7, 2)->nullable();
            $table->decimal('total_fat_100_reconstitued', 7, 2)->nullable();
            $table->decimal('satured_fat_100_reconstitued', 7, 2)->nullable();
            $table->decimal('trans_fat_100_reconstitued', 7, 2)->nullable();
            $table->decimal('monosatured_fat_100_reconstitued', 7, 2)->nullable();
            $table->decimal('polyunsatured_fat_100_reconstitued', 7, 2)->nullable();
            $table->decimal('cholesterol_100_reconstitued', 7, 2)->nullable();
            $table->decimal('total_carbohydrate_100_reconstitued', 7, 2)->nullable();
            $table->decimal('available_carbohydrates_100_reconstitued', 7, 2)->nullable();
            $table->decimal('total_sugars_100_reconstitued', 7, 2)->nullable();
            $table->decimal('sucrose_100_reconstitued', 7, 2)->nullable();
            $table->decimal('lactos_100_reconstitued', 7, 2)->nullable();
            $table->decimal('poliols_100_reconstitued', 7, 2)->nullable();
            $table->decimal('total_dietary_fiber_100_reconstitued', 7, 2)->nullable();
            $table->decimal('soluble_fiber_100_reconstitued', 7, 2)->nullable();
            $table->decimal('insoluble_fiber_100_reconstitued', 7, 2)->nullable();
            $table->decimal('sodium_100_reconstitued', 7, 2)->nullable();
            $table->decimal('energy_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('proteins_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('total_fat_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('satured_fat_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('trans_fat_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('monosatured_fat_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('polyunsatured_fat_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('cholesterol_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('total_carbohydrate_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('available_carbohydrates_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('total_sugars_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('sucrose_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('lactos_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('poliols_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('total_dietary_fiber_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('soluble_fiber_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('insoluble_fiber_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('sodium_serving_reconstitued', 7, 2)->nullable();
            $table->decimal('energy_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('proteins_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('total_fat_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('satured_fat_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('trans_fat_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('monosatured_fat_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('polyunsatured_fat_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('cholesterol_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('total_carbohydrate_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('available_carbohydrates_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('total_sugars_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('sucrose_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('lactos_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('poliols_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('total_dietary_fiber_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('soluble_fiber_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('insoluble_fiber_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('sodium_serving_reconstitued_r', 7, 2)->nullable();
            $table->decimal('vitamin_a_100', 7, 2)->nullable();
            $table->decimal('vitamin_c_100', 7, 2)->nullable();
            $table->decimal('vitamin_d_100', 7, 2)->nullable();
            $table->decimal('vitamin_e_100', 7, 2)->nullable();
            $table->decimal('vitamin_b1_100', 7, 2)->nullable();
            $table->decimal('vitamin_b2_100', 7, 2)->nullable();
            $table->decimal('niacin_100', 7, 2)->nullable();
            $table->decimal('vitamin_b6_100', 7, 2)->nullable();
            $table->decimal('folic_acid_100', 7, 2)->nullable();
            $table->decimal('vitamin_b12_100', 7, 2)->nullable();
            $table->decimal('pantothenic_acid_100', 7, 2)->nullable();
            $table->decimal('biotin_100', 7, 2)->nullable();
            $table->decimal('choline_100', 7, 2)->nullable();
            $table->decimal('vitamin_k_100', 7, 2)->nullable();
            $table->decimal('betacarotene_100', 7, 2)->nullable();
            $table->decimal('calcium_100', 7, 2)->nullable();
            $table->decimal('chromium_100', 7, 2)->nullable();
            $table->decimal('copper_100', 7, 2)->nullable();
            $table->decimal('yodo_100', 7, 2)->nullable();
            $table->decimal('iron_100', 7, 2)->nullable();
            $table->decimal('magnesium_100', 7, 2)->nullable();
            $table->decimal('manganese_100', 7, 2)->nullable();
            $table->decimal('molybdenum_100', 7, 2)->nullable();
            $table->decimal('phosphorus_100', 7, 2)->nullable();
            $table->decimal('zinc_100', 7, 2)->nullable();
            $table->decimal('selenium_100', 7, 2)->nullable();
            $table->decimal('vitamin_a_serving', 7, 2)->nullable();
            $table->decimal('vitamin_c_serving', 7, 2)->nullable();
            $table->decimal('vitamin_d_serving', 7, 2)->nullable();
            $table->decimal('vitamin_e_serving', 7, 2)->nullable();
            $table->decimal('vitamin_b1_serving', 7, 2)->nullable();
            $table->decimal('vitamin_b2_serving', 7, 2)->nullable();
            $table->decimal('niacin_serving', 7, 2)->nullable();
            $table->decimal('vitamin_b6_serving', 7, 2)->nullable();
            $table->decimal('folic_acid_serving', 7, 2)->nullable();
            $table->decimal('vitamin_b12_serving', 7, 2)->nullable();
            $table->decimal('pantothenic_acid_serving', 7, 2)->nullable();
            $table->decimal('biotin_serving', 7, 2)->nullable();
            $table->decimal('choline_serving', 7, 2)->nullable();
            $table->decimal('vitamin_k_serving', 7, 2)->nullable();
            $table->decimal('betacarotene_serving', 7, 2)->nullable();
            $table->decimal('calcium_serving', 7, 2)->nullable();
            $table->decimal('chromium_serving', 7, 2)->nullable();
            $table->decimal('copper_serving', 7, 2)->nullable();
            $table->decimal('yodo_serving', 7, 2)->nullable();
            $table->decimal('iron_serving', 7, 2)->nullable();
            $table->decimal('magnesium_serving', 7, 2)->nullable();
            $table->decimal('manganese_serving', 7, 2)->nullable();
            $table->decimal('molybdenum_serving', 7, 2)->nullable();
            $table->decimal('phosphorus_serving', 7, 2)->nullable();
            $table->decimal('zinc_serving', 7, 2)->nullable();
            $table->decimal('selenium_serving', 7, 2)->nullable();
            $table->string('total_aflatoxins',50)->nullable();
            $table->string('aflatoxina_m1',50)->nullable();
            $table->string('zearalenone',50)->nullable();
            $table->string('patulin',50)->nullable();
            $table->string('ochratoxin',50)->nullable();
            $table->string('deoxynivalenol',50)->nullable();
            $table->string('fumonisinas',50)->nullable();
            $table->string('zn',50)->nullable();
            $table->string('pb',50)->nullable();
            $table->string('cd',50)->nullable();
            $table->string('hg',50)->nullable();
            $table->string('sn',50)->nullable();
            $table->string('cu',50)->nullable();
            $table->string('ars',50)->nullable();
            $table->string('se',50)->nullable();
            $table->string('chloramphenicol',50)->nullable();
            $table->string('sulfonamides',50)->nullable();
            $table->string('tetracycline',50)->nullable();
            $table->string('quinolones',50)->nullable();
            $table->string('macrolides',50)->nullable();
            $table->string('betalactams',50)->nullable();
            $table->string('amphenicols',50)->nullable();
            $table->string('steroids',50)->nullable();
            $table->string('zeranol',50)->nullable();
            $table->string('pesticides',50)->nullable();
            $table->string('dioxin_furan',50)->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('productos_solicitud_importados_aca');
    }
};
