<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('productos_solicitud_importados_aca2', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
            $table->integer('id_producto')->nullable();
            $table->integer('id_solicitud')->nullable();
            $table->longText('sap')->nullable();
            $table->longText('product_name')->nullable();
            $table->longText('claims_origin')->nullable();
            $table->longText('comments')->nullable();
            $table->longText('name_organic_certifying_number')->nullable();
            $table->longText('plant_number_factory')->nullable();
            $table->longText('net_weight')->nullable();
            $table->longText('drained_weight')->nullable();
            $table->longText('units_x_packaging')->nullable();
            $table->longText('country')->nullable();
            $table->longText('milking_country')->nullable();
            $table->longText('expiration_date')->nullable();
            $table->longText('name_adress_manufacturer')->nullable();
            $table->longText('shelf_life')->nullable();
            $table->longText('upc_bar_code')->nullable();
            $table->longText('storage_conditions')->nullable();
            $table->longText('method_preparation')->nullable();
            $table->longText('name_supplier')->nullable();
            $table->longText('ingredients')->nullable();
            $table->longText('porcent_organic_ingredients')->nullable();
            $table->longText('porcent_characterizing_ingredients')->nullable();
            $table->longText('quantity_additive')->nullable();
            $table->longText('vegetable_oil_fat_used')->nullable();
            $table->longText('trans_fats_hydrogenated_origin')->nullable();
            $table->longText('spices_herbs_used')->nullable();
            $table->longText('quantity_sweetener_per_100_gr_ml')->nullable();
            $table->longText('flavourings_aroma_natural_artificial')->nullable();
            $table->longText('quantity_x_m_s_g')->nullable();
            $table->longText('quantity_caffeine')->nullable();
            $table->longText('any_extract_used')->nullable();
            $table->longText('origin_gelatin')->nullable();
            $table->longText('brix_final_product')->nullable();
            $table->longText('brix_final_product_without_added_sugar')->nullable();
            $table->longText('brix_fruit_greater_proportion_drink')->nullable();
            $table->longText('names_colourings')->nullable();
            $table->longText('minimum_porcent_cocoa_solids')->nullable();
            $table->longText('porcent_cocoa_butter_cocoa_mass')->nullable();
            $table->longText('contain_potential_allergens')->nullable();
            $table->longText('list_contain_potential_allergens')->nullable();
            $table->longText('cereals_gluten')->nullable();
            $table->longText('crustacean_products')->nullable();
            $table->longText('egg_derivatives')->nullable();
            $table->longText('fish_derivatives')->nullable();
            $table->longText('peanuts_soy_derivatives')->nullable();
            $table->longText('milk_dairy_derivatives')->nullable();
            $table->longText('nuts_derivatives')->nullable();
            $table->longText('sulfites_derivatives')->nullable();
            $table->longText('health_certificate')->nullable();
            $table->longText('organic_certification')->nullable();
            $table->longText('certification_free_afp')->nullable();
            $table->longText('thermograph')->nullable();
            $table->longText('gmo_information')->nullable();
            $table->longText('list_gmo_information')->nullable();
            $table->longText('total_plate_count')->nullable();
            $table->longText('staphylococcus')->nullable();
            $table->longText('mold')->nullable();
            $table->longText('coliform')->nullable();
            $table->longText('clostridium_perfringens')->nullable();
            $table->longText('yeast')->nullable();
            $table->longText('e_coli')->nullable();
            $table->longText('listeria_monocytogenes')->nullable();
            $table->longText('salmonella')->nullable();
            $table->longText('e_coli_0157_h7')->nullable();
            $table->longText('trichinella_spiralis')->nullable();
            $table->longText('lactobacillus')->nullable();
            $table->longText('campylobacter')->nullable();
            $table->longText('enterobacteria')->nullable();
            $table->longText('thermophilic_commercial_sterility')->nullable();
            $table->longText('bacillus_cereus')->nullable();
            $table->longText('ph')->nullable();
            $table->longText('porcent_aw')->nullable();
            $table->longText('type_primary_packaging')->nullable();
            $table->longText('type_secundary_packaging')->nullable();
            $table->longText('type_controls_sealing_air_tightness_primary_packaging')->nullable();
            $table->longText('product_type')->nullable();
            $table->longText('serving_size')->nullable();
            $table->longText('servings_per_container')->nullable();
            $table->longText('energy')->nullable();
            $table->longText('proteins')->nullable();
            $table->longText('total_fat')->nullable();
            $table->longText('satured_fat')->nullable();
            $table->longText('trans_fat')->nullable();
            $table->longText('monosatured_fat')->nullable();
            $table->longText('polyunsatured_fat')->nullable();
            $table->longText('cholesterol')->nullable();
            $table->longText('total_carbohydrate')->nullable();
            $table->longText('available_carbohydrates')->nullable();
            $table->longText('total_sugars')->nullable();
            $table->longText('sucrose')->nullable();
            $table->longText('lactos')->nullable();
            $table->longText('poliols')->nullable();
            $table->longText('total_dietary_fiber')->nullable();
            $table->longText('soluble_fiber')->nullable();
            $table->longText('insoluble_fiber')->nullable();
            $table->longText('sodium')->nullable();
            $table->longText('vitamin_a')->nullable();
            $table->longText('vitamin_c')->nullable();
            $table->longText('vitamin_d')->nullable();
            $table->longText('vitamin_e')->nullable();
            $table->longText('vitamin_b1')->nullable();
            $table->longText('vitamin_b2')->nullable();
            $table->longText('niacin')->nullable();
            $table->longText('vitamin_b6')->nullable();
            $table->longText('folic_acid')->nullable();
            $table->longText('vitamin_b12')->nullable();
            $table->longText('pantothenic_acid')->nullable();
            $table->longText('biotin')->nullable();
            $table->longText('choline')->nullable();
            $table->longText('vitamin_k')->nullable();
            $table->longText('betacarotene')->nullable();
            $table->longText('calcium')->nullable();
            $table->longText('chromium')->nullable();
            $table->longText('copper')->nullable();
            $table->longText('yodo')->nullable();
            $table->longText('iron')->nullable();
            $table->longText('magnesium')->nullable();
            $table->longText('manganese')->nullable();
            $table->longText('molybdenum')->nullable();
            $table->longText('phosphorus')->nullable();
            $table->longText('zinc')->nullable();
            $table->longText('selenium')->nullable();
            $table->longText('haccp')->nullable();
            $table->longText('others_certifications')->nullable();
            $table->longText('total_aflatoxins')->nullable();
            $table->longText('aflatoxina_m1')->nullable();
            $table->longText('zearalenone')->nullable();
            $table->longText('patulin')->nullable();
            $table->longText('ochratoxin')->nullable();
            $table->longText('deoxynivalenol')->nullable();
            $table->longText('fumonisinas')->nullable();
            $table->longText('zn')->nullable();
            $table->longText('pb')->nullable();
            $table->longText('cd')->nullable();
            $table->longText('hg')->nullable();
            $table->longText('sn')->nullable();
            $table->longText('cu')->nullable();
            $table->longText('ars')->nullable();
            $table->longText('se')->nullable();
            $table->longText('chloramphenicol')->nullable();
            $table->longText('tetracycline')->nullable();
            $table->longText('quinolones')->nullable();
            $table->longText('sulfonamides')->nullable();
            $table->longText('pesticides')->nullable();
            $table->longText('dioxin_furan')->nullable();
            $table->longText('esteroides')->nullable();
            $table->longText('gluten_free')->nullable();
            $table->longText('hidroxianthracene')->nullable();
            $table->longText('aloine')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('productos_solicitud_importados_aca2');
    }
};
